import { describe, it, expect } from 'vitest'
import { browseExpenses, browserMonths } from './expenseFilter'
import type { Expense, Recurring } from './expense'

const exp = (
  id: string,
  date: string,
  category: Expense['category'],
  note?: string
): Expense => ({
  id,
  amount: 10,
  category,
  date,
  note,
  createdAt: date,
})

const template = (over: Partial<Recurring>): Recurring => ({
  id: 't1',
  amount: 800,
  category: 'Rent',
  dayOfMonth: 1,
  active: true,
  createdAt: '2026-03-05',
  ...over,
})

describe('browseExpenses (BR-LST-1, TICKET-044)', () => {
  const expenses = [
    exp('a', '2026-08-01', 'Groceries', 'lidl run'),
    exp('b', '2026-08-05', 'Restaurants & drinks', 'pizza'),
    exp('c', '2026-07-20', 'Groceries'),
  ]

  it('lists one-off + recurring rows for the month', () => {
    const rows = browseExpenses(expenses, [template({})], {
      month: '2026-08',
    })
    expect(rows.map((r) => r.id)).toEqual(['a', 'b', 't1:2026-08'])
  })

  it('filters by category including legacy values in use', () => {
    const legacy = [exp('old', '2026-08-02', 'Food' as Expense['category'])]
    const rows = browseExpenses([...expenses, ...legacy], [], {
      month: '2026-08',
      category: 'Food',
    })
    expect(rows.map((r) => r.id)).toEqual(['old'])
  })

  it('searches note + category, case-insensitive', () => {
    expect(
      browseExpenses(expenses, [], { month: '2026-08', query: 'LIDL' }).map(
        (r) => r.id
      )
    ).toEqual(['a'])
    expect(
      browseExpenses(expenses, [], { month: '2026-08', query: 'resta' }).map(
        (r) => r.id
      )
    ).toEqual(['b'])
  })

  it('composes month AND category AND text', () => {
    const rows = browseExpenses(expenses, [], {
      month: '2026-07',
      category: 'Groceries',
      query: 'x',
    })
    expect(rows).toEqual([])
  })
})

describe('browserMonths (TICKET-044)', () => {
  it('returns data months plus current, newest first', () => {
    const months = browserMonths(
      [exp('a', '2026-06-01', 'Rent')],
      [],
      '2026-08'
    )
    expect(months).toEqual(['2026-08', '2026-06'])
  })

  it('includes months generated by recurring templates', () => {
    const months = browserMonths([], [template({})], '2026-08')
    expect(months).toEqual([
      '2026-08',
      '2026-07',
      '2026-06',
      '2026-05',
      '2026-04',
      '2026-03',
    ])
  })
})
